apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "www.fullname" . }}-seed
  labels:
    {{- include "www.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "www.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: seed
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "www.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: seed
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - "bun run db:push && bun run db:seed"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: zeyaddeeb-secrets
                  key: "ADMIN_EMAIL"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zeyaddeeb-secrets
                  key: "ADMIN_PASSWORD"
            - name: ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: zeyaddeeb-secrets
                  key: "ADMIN_NAME"
            - name: ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: zeyaddeeb-secrets
                  key: "ADMIN_ID"
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range .Values.envFromSecrets }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secName }}
                  key: {{ .secValue }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
