[package]
edition = "2021"
name = "zeyaddeeb-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.108"
js-sys = "0.3"
rustfft = "6.2"

[profile.release]
opt-level = 3
lto = true
